- name: Install packages
  ansible.builtin.import_tasks: packages.yaml
  become: true

- name: Enable common services
  ansible.builtin.import_tasks: services.yaml
  become: true

- name: Set common configs
  ansible.builtin.import_tasks: users.yaml
  become: true

- name: Install ebpf-net-exporter
  ansible.builtin.include_tasks: ebpf_net_exporter.yaml
  when: host_type == 'server'

- name: Install node_exporter
  ansible.builtin.import_tasks: node_exporter.yaml

- name: Install fail2ban-exporter
  ansible.builtin.import_tasks: fail2ban_exporter.yaml
