- name: Install packages for Debian
  ansible.builtin.import_tasks: debian/packages.yaml
  when: ansible_facts['os_family']|lower == "debian"

- name: Install packages for Redhat
  ansible.builtin.import_tasks: redhat/packages.yaml
  when: ansible_facts['os_family']|lower == "redhat"
