all:
  vars:
    ansible_connection: ssh
    ansible_user: elw
    ansible_port: 22
  children:
    laptops:
      hosts:
        xbook2:
          ansible_host: 127.0.0.1
      vars:
        host_type: workstation
    servers:
      hosts:
        jupiter:
          ansible_host: jupiter.tail167587.ts.net
        jumpstar:
          ansible_host: jumpstar.tail167587.ts.net
        ministar:
          ansible_host: ministar.tail167587.ts.net
      vars:
        host_type: server
    external:
      hosts:
        mail:
          ansible_host: mail.xy0.org
      vars:
        host_type: server
