all:
  vars:
    ansible_connection: ssh
    ansible_user: elw
    ansible_port: 22
  children:
    laptops:
      hosts:
        smackbook:
          ansible_host: 127.0.0.1
          ansible_user: twood5
        xbook2:
          ansible_host: 127.0.0.1
      vars:
        host_type: workstation
    servers:
      hosts:
        jupiter:
          ansible_host: 192.168.1.101
      vars:
        host_type: server
