---
- name: Jupiter Setup
  hosts: jupiter
  become: true
  tasks:
    - name: Install Packages
      block:
        - name: Install basic dependencies
          ansible.builtin.apt:
            name:
              - tmux
              - ca-certificates
              - curl
              - gnupg
              - lsb-release
              - zfsutils-linux
              - apt-transport-https
            state: present
    - name: Docker Setup
      block:
        - name: Add docker apt key
          ansible.builtin.get_url:
            url: https://download.docker.com/linux/ubuntu/gpg
            dest: /etc/apt/trusted.gpg.d/docker.asc
            mode: 0644
        - name: Add docker repo
          ansible.builtin.apt_repository:
            repo: "deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/docker.asc] https://download.docker.com/linux/ubuntu jammy stable"
        - name: Install docker and dependencies
          ansible.builtin.apt:
            name:
              - docker-ce
              - docker-ce-cli
              - containerd.io
              - docker-compose-plugin
            state: present
        - name: Ensure Docker is running
          ansible.builtin.service:
            name: docker
            state: started
        - name: Ensure user in docker group
          ansible.builtin.user:
            name: elw
            group: elw
            shell: /bin/bash
            groups: docker
            append: true
    - name: Enable Standard Services
      block:
        - name: Enable ssh
          ansible.builtin.service:
            name: ssh
            state: started
    - name: Configure Storage Layout
      block:
        - name: Create Zpool
          ansible.builtin.command: zpool create tank raidz2 sdc sdd sde sdf sdg sdh sdi sdj
          args:
            creates: /tank