---
- name: Jupiter Setup
  hosts: jupiter
  become: true
  vars:
    local_users:
      - elw
  tasks:
    - name: Get all groups
      ansible.builtin.getent:
        database: group
        split: ':'
    - name: Install Packages
      block:
        - name: Install basic dependencies
          ansible.builtin.apt:
            name:
              - tmux
              - ca-certificates
              - curl
              - gnupg
              - lsb-release
              - apt-transport-https
            state: present
    - name: Enable Standard Services
      block:
        - name: Enable ssh
          ansible.builtin.service:
            name: ssh
            state: started
    - name: Create local users
      ansible.builtin.user:
        name: "{{ item }}"
        shell: /bin/bash
        state: present
      loop: "{{ local_users }}"
    - name: Add local users to docker group
      ansible.builtin.user:
        name: "{{ item }}"
        state: present
        groups: docker
        append: true
      loop: "{{ local_users }}"
      when: '"docker" in ansible_facts.getent_group'
  roles:
    - role: raven-node
    - role: docker
    - role: zpool
      vars:
        pool_members: "sdc sdd sde sdf sdg sdh sdi sdj"
        pool_type: "raidz2"
        pool_name: "tank"
        zfs_filesystems: [{path: "tank/rvn", quota: "214748364800"}]
