---
- name: Mail Server Setup
  hosts: mail
  become: true
  vars:
    local_users:
      - userid: elw
        gh_id: tedwardd
        sudo: true
    fail2ban_exporter_enabled: true
  pre_tasks:
    - name: Install UFW
      ansible.builtin.apt:
        name: ufw
        state: present
        update_cache: true

    - name: Allow SSH before enabling UFW
      community.general.ufw:
        rule: allow
        port: "22"
        proto: tcp

    - name: Enable UFW with default deny
      community.general.ufw:
        state: enabled
        policy: deny
        direction: incoming
  roles:
    - role: linux_common
    - role: certbot
    - role: opendkim
    - role: postfix
    - role: dovecot
    - role: oefenweb.fail2ban
    - role: promtail
