---
- name: Jumpstar Setup
  hosts: jumpstar
  become: true
  vars:
    local_users:
      - userid: elw
        gh_id: tedwardd
        sudo: true
    fail2ban_services:
      - name: sshd
        port: 22
        maxretry: 5
        bantime: 1h
        bantime_increment: true
        bantime_factor: 2
        backend: systemd
      - name: nginx-http-auth
        port: http,https
        logpath: /var/log/nginx/error.log
        maxretry: 5
      - name: nginx-botsearch
        port: http,https
        logpath: /var/log/nginx/access.log
        maxretry: 2
      - name: nginx-bad-request
        port: http,https
        logpath: /var/log/nginx/access.log
        maxretry: 5
      - name: recidive
        logpath: /var/log/fail2ban.log
        bantime: 1w
        findtime: 1d
        maxretry: 5
  roles:
    - role: linux_common
    - role: oefenweb.fail2ban
- name: Jupiter Setup
  hosts: jupiter
  become: true
  vars:
    local_users:
      - userid: elw
        gh_id: tedwardd
        sudo: true
  roles:
    - role: docker
    - role: linux_common
    - role: virt_host
    - role: prometheus.prometheus.prometheus
    - role: cf_dns_discovery
  tasks:
    - name: Make zpool
      zpool:
        name: tank
        devices:
          - sdc
          - sdd
          - sde
          - sdf
          - sdg
          - sdh
          - sdi
        raid_level: raidz2
        vdev: 7
        state: present
    - name: Create ZFS Filesystems
      community.general.zfs:
        name: 'tank/rvn'
        state: present
        extra_zfs_properties:
          quota: "214748364800" # Must be defined in bytes
