---
- name: Xbook2 Setup
  hosts: xbook2
  vars:
    local_users:
      - userid: elw
        gh_id: tedwardd
        sudo: true
  roles:
    - role: linux_common
    - role: vagrant
      req_vagrant_plugins:
        - vagrant-libvirt
  tasks:
    - name: Install vagrant-libvirt deps
      ansible.builtin.apt:
        name:
          - qemu-system-common
          - qemu-user
          - libvirt-daemon-system
          - ebtables
          - libguestfs-tools
          - libxslt-dev
          - libxml2-dev
          - zlib1g-dev
          - ruby-dev
          - libvirt-dev
          - ruby-libvirt
      become: true
- name: MiniStar Configs
  hosts: ministar
  vars:
    local_users:
      - userid: elw
        gh_id: tedwardd
        sudo: true
  roles:
    - role: linux_common
