---
- name: Install Vagrant GPG key and add apt source
  ansible.builtin.include_tasks:
    file: gpg.yaml

- name: Install vagrant application
  ansible.builtin.include_tasks:
    file: install.yaml

- name: Install vagrant plugins
  ansible.builtin.include_tasks:
    file: plugins.yaml
