---
- name: Install Postfix
  ansible.builtin.apt:
    name:
      - postfix
      - mailutils
    state: present
    update_cache: true

- name: Deploy main.cf
  ansible.builtin.template:
    src: main.cf.j2
    dest: /etc/postfix/main.cf
    owner: root
    group: root
    mode: "0644"
  notify: Reload postfix

- name: Deploy virtual alias map
  ansible.builtin.template:
    src: virtual.j2
    dest: /etc/postfix/virtual
    owner: root
    group: root
    mode: "0644"
  notify: Rebuild virtual map

- name: Enable and start Postfix
  ansible.builtin.systemd:
    name: postfix
    enabled: true
    state: started

- name: Open SMTP port in UFW
  community.general.ufw:
    rule: allow
    port: "25"
    proto: tcp

- name: Open submission port in UFW
  community.general.ufw:
    rule: allow
    port: "587"
    proto: tcp
