---
- name: Restart ebpf-net-exporter
  ansible.builtin.systemd:
    name: ebpf-net-exporter
    state: restarted
    daemon_reload: true
  ignore_errors: "{{ ansible_check_mode }}"

- name: Restart fail2ban-exporter-timer
  ansible.builtin.systemd:
    name: fail2ban-exporter.timer
    state: restarted
    daemon_reload: true
