#!/bin/bash

function usage() {
    cat << EOF
Usage: TODO
EOF
}

if [[ $# -eq 0 ]]; then
    usage
    exit 1
fi

host="$1"
debug="${2:-debug=false}"
debug=$(awk -F"=" '{print $2}' <<< "${debug}")

[[ "${debug}" == "true" ]] && ansible-playbook -i hosts.yaml "${host}".yaml -K -C
[[ "${debug}" == "false" ]] && ansible-playbook -i hosts.yaml "${host}".yaml -K