- name: Install zfs packages
  ansible.builtin.apt:
    name:
      - zfsutils-linux
    state: present

- name: Configure zpool
  ansible.builtin.import_tasks: pool.yaml
  when: pool_members is defined

- name: Create zfs filesystems
  ansible.builtin.import_tasks: filesystem.yaml
  when: zfs_filesystems is defined and zpool_exists is defined
