- name: Install Common Packages
  ansible.builtin.apt:
    name:
      - tmux
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
      - apt-transport-https
      - genisoimage
    state: present
  when: ( ansible_facts['os_family'] == "Ubuntu" or ansible_facts['os_family'] == "Debian")
